# Generated by Django 6.0.3 on 2026-06-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Rapor Görseli')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
                ('address', models.TextField(default='Adres belirtilmedi', verbose_name='Adres')),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='Yapay Zeka Açıklaması')),
                ('ai_risk_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yapay Zeka Risk Seviyesi')),
                ('user_notes', models.TextField(blank=True, null=True, verbose_name='Kullanıcı Ek Notu')),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandı', 'Onaylandı'), ('çözüldü', 'Çözüldü'), ('reddedildi', 'Reddedildi'), ('analiz_hatasi', 'Analiz Hatası')], default='beklemede', max_length=30, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Raporlayan Vatandaş')),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
